[package]
name = "patstrap-rs"
repository = "https://github.com/danielfvm/patstrap"
description = "Server program that acts as a bridge between VRChat and the patstrap device"
authors = [ "DeanCode" ]
version = "0.0.3"
edition = "2024"

# https://axodotdev.github.io/cargo-dist/book/quickstart/rust.html
[package.metadata.wix]
upgrade-guid = "84D954CA-583D-464A-BD2F-EB839C0D1587"
path-guid = "285D0AC2-7DE2-4DE7-8860-A3C6F05E32AE"
license = false
eula = false

[dependencies]
eframe = "0.33.3"
strum = "0.28"
strum_macros = "0.28"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.0", features = ["derive"] }
serde_json = "1.0.149"
btleplug = "0.12.0"
futures-util = "0.3.32"
tokio = { version = "1.50.0", features = ["full"] }
uuid = "1.22.0"
mdns-sd = "0.19.0"
tokio-util = "0.7.18"
vrchat_osc = "2"
anyhow = "1.0.102"
log = "0.4.29"
env_logger = "0.11"
planck-pack = "0.1.1"
async-trait = "0.1.89"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
opt-level = "z"
codegen-units = 1
panic = "abort"
strip = true
